# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  moneymapapi:
    image: moneymapapi
    build:
      context: .
      dockerfile: MoneyMap.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5028:5028
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
