services:
  api:
    build:
      context: .
      dockerfile: MoneyMap.Api/Dockerfile
    container_name: moneymap-api
    depends_on:
      sqlserver:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=MoneyMapDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
      Database__ApplyMigrationsOnStartup: "true"
      Jwt__Issuer: MoneyMap.Api
      Jwt__Audience: MoneyMap.Client
      Jwt__Key: moneymap-super-secret-jwt-key-please-change-me
      Jwt__ExpiryMinutes: "120"
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: moneymap-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: Express
    ports:
      - "14333:1433"
    volumes:
      - moneymap-sqldata:/var/opt/mssql

volumes:
  moneymap-sqldata:
